name: Tests

on: push

jobs:

  passage_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Installation de java-17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Compilation et lance les tests
        run: mvn test
